export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';

export const UPDATE_SEARCH_TERM = 'UPDATE_SEARCH_TERM';
export const UPDATE_GROUP_BY = 'UPDATE_GROUP_BY';
export const UPDATE_SELECTION = 'UPDATE_SELECTION';

export const ADD_TERM = 'ADD_TERM';
export const ADD_PRICE_TERM = 'ADD_PRICE_TERM';
export const REMOVE_TERM = 'REMOVE_TERM';
export const REMOVE_ALL_TERMS = 'REMOVE_ALL_TERMS';

export const SORT_RESULTS = 'SORT_RESULTS';
export const UPDATE_RESULTS_PER_PAGE = 'UPDATE_RESULTS_PER_PAGE';
export const UPDATE_FIRST_RESULT_DISPLAY = 'UPDATE_FIRST_RESULT_DISPLAY';
